### ISSUE TITLE
For disconnected installs, consider mirroring the machine OS image as well

### ISSUE THREAD

**Issue by stbenjam** [openshift-kni/baremetal-deploy#103]
Installation requires downloading 2 machine OS images to install the bootstrap and the control plane and worker nodes, which typically happens over the internet.

For the boostrap, we use the QEMU RHCOS image, and for other hosts we use the OpenStack image which has the appropriate support for disconnected installs.

To set local locations for these images, update the install-config:

```yaml
platform:
  baremetal:
    bootstrapOSImage: http://<local mirror>>/rhcos-43.81.201912131630.0-qemu.x86_64.qcow2.gz?sha256=XYZ'
    clusterOSImage: http://<local mirror>/rhcos-43.81.201912131630.0-openstack.x86_64.qcow2.gz?sha256=XYZ'
```

Notes:

- You may provide a URL to the gzipped image, or the uncompressed image, but in BOTH cases, the installer only verifies the hash after decompressing (this may change https://github.com/openshift/installer/issues/2845)

- To identify which images to download and the appropriate hashes, you can see how dev-scripts does it @ https://github.com/openshift-metal3/dev-scripts/blob/master/rhcos.sh
