### ISSUE TITLE
Missing platform.baremetal.provisioningNetworkInterface in install-config.yaml

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#160]
When running the `TASK [installer : Create OpenShift Manifest] ***********************************` tasks, it fails because:

```
    "stderr": "level=fatal msg=\"failed to fetch Master Machines: failed to load asset \\\"Install Config\\\": invalid \\\"install-config.yaml\\\" file: platform.baremetal.provisioningNetworkInterface: Invalid value: \\\"\\\": no provisioning network interface is configured, please set this value to be the interface on the provisioning network on your cluster's baremetal hosts\"", 
```

My install-config.yaml generated by the playbook contains:

```
apiVersion: v1
baseDomain: xxx
metadata:
  name: xxx
networking:
  machineCIDR: xxx
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: xxx
    ingressVIP: xxx
    dnsVIP: xxx
    hosts:
xxx
```
And according to https://github.com/openshift/installer/blob/master/docs/user/metal/install_ipi.md#install-config it requires `platform.baremetal.provisioningNetworkInterface`
