### ISSUE TITLE
Error while provisioning workers (blockdev: cannot open /dev/sda: No medium found)

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#165]
```
openshift-machine-api   kni1-worker-0   error    provisioning             kni1-worker-0-r7gcg   ipmi://10.19.143.29   unknown            true     Image provisioning failed: node f7819fc2-50ee-4b25-bb9b-3269f3ffac85 command status errored: {'type': 'ImageWriteError', 'code': 500, 'message': 'Error writing image to device: Writing image to device /dev/sda failed with exit code 1. stdout: write_image.sh: Erasing existing GPT and MBR data structures from /dev/sda\n. stderr: blockdev: cannot open /dev/sda: No medium found\n', 'details': 'Writing image to device /dev/sda failed with exit code 1. stdout: write_image.sh: Erasing existing GPT and MBR data structures from /dev/sda\n. stderr: blockdev: cannot open /dev/sda: No medium found\n'}
```
```
Client Version: 4.3.1
Server Version: 4.3.1
Kubernetes Version: v1.16.2
```
```
      - name: kni1-worker-0
        role: worker
        bmc:
          address: ipmi://xxx
          username: root
          password: xxx
        bootMACAddress: xxx
        hardwareProfile: unknown
```
