### ISSUE TITLE
Setting ipv6_enabled true and ipv4_baremetal true gives wrong install-config info

### ISSUE THREAD

**Issue by rlopez133** [openshift-kni/baremetal-deploy#343]
When enabling both ipv6_enabled=True and ipv4_baremetal=True you get the 
```
  clusterNetwork:
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
  - fd02::/112
```
to be set within the install-config. Need to fix this so its not included when ipv4_baremetal is set to True
