### ISSUE TITLE
Generate install-config task causing extra indentation under platform

### ISSUE THREAD

**Issue by vakhanna** [openshift-kni/baremetal-deploy#436]
Install config results in having extra white spaces before dnsvip and provisioningBridge.

```
platform:
  baremetal:
    apiVIP: 10.1.24.10
    ingressVIP: 10.1.24.11
        dnsVIP: 10.1.24.12
        provisioningBridge: provisioning
```

The issue is likely due to extra spaces in the install config template if condition here.
https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/installer/templates/install-config.j2#L33
