### ISSUE TITLE
Deployment fails when install-config.yaml hosts do not include master nodes first 

### ISSUE THREAD

**Issue by mcornea** [openshift-kni/baremetal-deploy#75]
With the following install-config.yaml:

```yaml
[kni@worker-1 ~]$ cat install-config.yaml 
apiVersion: v1
baseDomain: qe.lab.redhat.com
networking:
  machineCIDR: 192.168.123.0/24
metadata:
  name: ocp-edge-cluster
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.123.5
    dnsVIP: 192.168.123.6
    ingressVIP: 192.168.123.10
    hosts:
      - name: openshift-master-2
        role: master
        bmc:
          address: ipmi://192.168.123.1:6232
          username: admin
          password: password
        bootMACAddress: 52:54:00:88:41:e0
        hardwareProfile: default
      - name: openshift-worker-0
        role: worker
        bmc:
          address: ipmi://192.168.123.1:6233
          username: admin
          password: password
        bootMACAddress: 52:54:00:cd:0a:b1
        hardwareProfile: unknown
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://192.168.123.1:6230
          username: admin
          password: password
        bootMACAddress: 52:54:00:5f:b0:ef
        hardwareProfile: default
      - name: openshift-master-1
        role: master
        bmc:
          address: ipmi://192.168.123.1:6231
          username: admin
          password: password
        bootMACAddress: 52:54:00:73:53:97
        hardwareProfile: default
```

Deployment fails because the installer deployed:
- openshift-master-2
- openshift-worker-0
- openshift-master-0

Note: deployment works correctly when I put master nodes first in the hosts list:

```yaml
apiVersion: v1
baseDomain: qe.lab.redhat.com
networking:
  machineCIDR: 192.168.123.0/24
metadata:
  name: ocp-edge-cluster
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.123.5
    dnsVIP: 192.168.123.6
    ingressVIP: 192.168.123.10
    hosts:
      - name: openshift-master-2
        role: master
        bmc:
          address: ipmi://192.168.123.1:6232
          username: admin
          password: password
        bootMACAddress: 52:54:00:88:41:e0
        hardwareProfile: default
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://192.168.123.1:6230
          username: admin
          password: password
        bootMACAddress: 52:54:00:5f:b0:ef
        hardwareProfile: default
      - name: openshift-master-1
        role: master
        bmc:
          address: ipmi://192.168.123.1:6231
          username: admin
          password: password
        bootMACAddress: 52:54:00:73:53:97
        hardwareProfile: default
      - name: openshift-worker-0
        role: worker
        bmc:
          address: ipmi://192.168.123.1:6233
          username: admin
          password: password
        bootMACAddress: 52:54:00:cd:0a:b1
        hardwareProfile: unknown
```

[kni@worker-1 ~]$ echo $VERSION
4.3.0-0.nightly-2019-12-09-035405
[kni@worker-1 ~]$ echo $RELEASE_IMAGE
quay.io/openshift-release-dev/ocp-release-nightly@sha256:52d9ac31e14658a3e48bc9a2ce041220b697008e59319a9ce009e269097c3706
